local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
amazon:
  service: S3
  access_key_id: "AKIAJTVTUBKFN7BA45SQ"
  secret_access_key: "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"
  bucket: "decreation"
  region: "us-west-2"